baseURL = "https://example.com"
enableEmoji = true
title = "Developer"
author = "Andrey Parfenov"
defaultContentLanguage = "en"
theme = "matter"

[languages]
  [languages.en]
    languageName="en"
    title="Developer"
    weight = 1
  [languages.ru]
    languageName="ru"
    title="Разрабротчик"
    weight = 2


[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]
  author = "Andrey Parfenov"
  fontAwesomeKit = "<script src='https://kit.fontawesome.com/1c61329d77.js' crossorigin='anonymous'></script>"

  [params.socials]
    facebook = ""
    twitter = ""
    instagram = ""
    youtube = ""
    github = "https://github.com/fourtyone11"
    gitlab = "https://gitlab.com/asleeppiano"
    linkedin = ""
    medium= ""

[[languages.en.menu.global]]
  name = "projects"
  weight = 1
  identifier = "projects"
  url = "/projects/"

[[languages.en.menu.global]]
  name = "blog"
  weight = 10
  identifier = "posts"
  url = "/posts/"

[[languages.en.menu.global]]
  name = "about"
  weight = 10
  identifier = "about"
  url = "/about/"

[[languages.ru.menu.global]]
  name = "проекты"
  weight = 1
  identifier = "projects"
  url = "/ru/projects/"

[[languages.ru.menu.global]]
  name = "блог"
  weight = 10
  identifier = "posts"
  url = "/ru/posts/"

[[languages.ru.menu.global]]
  name = "обо мне"
  weight = 15
  identifier = "about"
  url = "/ru/about/"

[outputs]
    home = [ "HTML", "JSON", "RSS" ]
    page = [ "HTML" ]

[markup.goldmark.renderer]
  unsafe = true

